q = dict(zip('abc', range(1, 4)))
w = dict(zip('cde', range(2, 5)))
print(q, w)
print(q | w)
# union = q.keys() | w.keys()
# print(union)
# d = q.keys()
# f = w.keys()
# print(d | f)
#
# print(q.keys() & w.keys())
# print(q.keys() - w.keys())
